################################################
# WiFI-Configuration
#
################################################
CIRCUITPY_WIFI_SSID="TP-LINK_7692"
CIRCUITPY_WIFI_PASSWORD="24136440"
CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_PASSWORD="obvious"
CIRCUITPY_HOST_NAME="DALYBMS"
thumbs_up="\U0001f44d"

################################################
# GENERAL
################################################
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
LOGLEVEL = 20
UART0_TX = "GP0"
UART0_RX = "GP1"
UART1_TX = "GP4"
UART1_RX = "GP5"

################################################
# DALY-BMS
################################################
BMS_DEMO="False"
BMS_VERSION = "V 0.1.0"
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
BMS_LOG_LEVEL = 3
BMS_INTERVAL = 3000
BMS_UART = 0

################################################
# HEART-BEAT
################################################
HEARTBEAT_INTERVAL = 5000
HEARTBEAT_IDLE_INTERVAL = 150
HEARTBEAT_ERROR_INTERVAL = 500
HEARTBEAT_IDLE = 1
HEARTBEAT_ERROR_BMS = 2
HEARTBEAT_ERROR_MODBUS = 3
HEARTBEAT_ERROR_INVERTER = 4
HEARTBEAT_ERROR_WLAN = 5
HEARTBEAT_ERROR_MQTT = 6


################################################
# SOYOSOURCE
################################################
SOYO_DEMO="True"
SOYO_WRITE_INTERVAL = 500
SOYO_INTERVAL = 15000
SOYO_VERSION = "V 0.1.0"
SOYO_UART = 1
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
SOYO_LOGLEVEL = 10

################################################
# EPEVER
################################################
EPEVER_DEMO="True"
EPEVER_INTERVAL = 5000
EPEVER_VERSION = "V 0.1.0"
EPEVER_UART=1
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
EPEVER_LOGLEVEL=20

################################################
# MQTT-Configuration
################################################
MQTT_BROKER_IP="127.0.0.1"
MQTT_PORT=1883
MQTT_PREFIX="RP2040_SOLAR"
MQTT_TOPIC="DALYBMS"
MQTT_USER="lunax"
MQTT_PW="granny.COPTER3opus"

#MQTT_BROKER_IP="192.168.0.240"
#MQTT_PORT=1883
#MQTT_PREFIX="RP2040_SOLAR"
#MQTT_TOPIC="DALYBMS"
#MQTT_USER="lunax"
#MQTT_PW="granny.COPTER3opus"
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
MQTT_LOGLEVEL=20
